### PR TITLE
Basic page structure

### PR DESCRIPTION
**Pull request by Gopxfs**
- Initialized Webpack configuration.
- Updated the readme file with project information.
- Created a basic interface using HTML.
- Added SCSS to adjust the HTML elements as in the wireframe.
- Added linters.

### CODE REVIEW

**Review by ShahierNashaat — CHANGES_REQUESTED** [review]
Hi @Gopxfs , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] Kindly write`node_modules` not `node_modules\` to make it work, and remove the node_modules folder from the github repo.
- [x] Kindly be noticed that the HTML code looks like in the [wireframe](https://github.com/microverseinc/curriculum-javascript/blob/main/leaderboard/images/leaderboard_wireframe.png), styling is not required for this project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gopxfs** [comment]
Hey! I don't get the first suggestion. I've already removed the nodes folder from the branch.
I also didn't understand the second suggestion, as the exercise says: _"Write plain HTML markup with minimum styling (just to make the layout), because you will implement styles in the following steps. Use this wireframe as a guide:"_ I used minimum styling to fit the layout.

**Comment by ShahierNashaat** [comment]
The first one means that you should remove the / from the node_modules in your gitignore file.
The second one you design the wireframe in your html file.

**Comment by Gopxfs** [comment]
> 

Oh, thanks for the advice. But I accidentally pushed the node_modules without a .gitignore file, the / works fine.

**Review by Oxford-G — APPROVED** [review]
Hi Gopxfs, 

Your project is complete!  There is nothing else to say other than... it's time to merge it .
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
